export const BANNER_PRESETS = {
  facebookCover: { name: 'Facebook Cover', width: 851, height: 315 },
  instagramPost: { name: 'Instagram Post', width: 270, height: 270 },
  instagramStory: { name: 'Instagram Story', width: 270, height: 480 },
  twitterHeader: { name: 'Twitter Header', width: 1500, height: 500 },
  linkedinBanner: { name: 'LinkedIn Banner', width: 1584, height: 396 },
  youtubeChannel: { name: 'YouTube Channel Art', width: 2560, height: 1440 },
};

export const FONT_OPTIONS = [
  { label: 'Poppins', value: 'Poppins', isHeadline: true },
  { label: 'Montserrat', value: 'Montserrat', isHeadline: true },
  { label: 'Oswald', value: 'Oswald', isHeadline: true },
  { label: 'Bebas Neue', value: 'Bebas Neue', isHeadline: true },
  { label: 'Anton', value: 'Anton', isHeadline: true },
  { label: 'Raleway', value: 'Raleway', isHeadline: true },
  { label: 'Playfair Display', value: 'Playfair Display', isHeadline: true },
  { label: 'Arvo', value: 'Arvo', isHeadline: true },
  { label: 'Slabo 27px', value: 'Slabo 27px', isHeadline: false },
  { label: 'PT Sans', value: 'PT Sans', isHeadline: false },
  { label: 'Roboto', value: 'Roboto', isHeadline: false },
  { label: 'Open Sans', value: 'Open Sans', isHeadline: false },
  { label: 'Source Sans Pro', value: 'Source Sans Pro', isHeadline: false },
  { label: 'Lato', value: 'Lato', isHeadline: false },
  { label: 'Nunito', value: 'Nunito', isHeadline: false },
  { label: 'Lora', value: 'Lora', isHeadline: false },
  { label: 'Merriweather', value: 'Merriweather', isHeadline: false },
  { label: 'Pacifico', value: 'Pacifico', isHeadline: true },
  { label: 'Dancing Script', value: 'Dancing Script', isHeadline: true },
  { label: 'Indie Flower', value: 'Indie Flower', isHeadline: true },
];
